# Generated by Django 4.0.5 on 2022-06-25 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.IntegerField(unique=True)),
                ('title', models.TextField(default='Lorem ipsum')),
                ('description', models.TextField(default='sit dor amet')),
            ],
        ),
    ]
