# Generated by Django 4.0.5 on 2022-07-14 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_bookuserstatus_publisher_review_series_book_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='author',
            name='twitter_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
