# Generated by Django 4.0.5 on 2022-08-24 17:21

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0008_alter_book_thumbnail_userfollowing'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookuserstatus',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 24, 17, 20, 57, 360593, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='timestamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='reviewcomment',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        # migrations.CreateModel(
        #     name='UserFollowing',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('following_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL)),
        #         ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL)),
        #     ],
        # ),
    ]
